### ISSUE TITLE
Pairing can't complete for board definition 2.2.0

### ISSUE THREAD

**Issue by duncanhoggan** [tcoppex/mbed-ble-hid#10]
When using the `Arduino Mbed OS Nano Boards` board definition with version 2.2.0 the initial pairing request fails indicating that the passphrase was wrong.

2.0.0 appears to work.

**Comment by tcoppex** [comment]
Hi @duncanhoggan,

Thanks for your feedbacks. I've just updated the repo and tested the examples via the OS Nano Boards version 2.5.2 without an issue against an Android device, so I'll close the issue. Feel free to reopen it if you still got it though.
