### ISSUE TITLE
Pairing failed

### ISSUE THREAD

**Issue by Moussabaddour** [tcoppex/mbed-ble-hid#14]
I uploaded ble_shining_kb to NANO 33 BLE and tried to pair with many Android , iOS phones  and PCs but always I got error in paring.!!!!!

**Comment by tcoppex** [comment]
Hi @Moussabaddour,

Yes, the current version is faulty and deprecated, I am working on a fix.
Please refer to issue https://github.com/tcoppex/mbed-ble-hid/issues/11
