### ISSUE TITLE
call of overloaded 'millis()' is ambiguous

### ISSUE THREAD

**Issue by erichstuder** [tcoppex/mbed-ble-hid#17]
I have a simple platformio project.
Compiling gives the following error:
```
.pio\libdeps\nano33ble\Mbed BLE HID\src\Mbed_BLE_HID.cpp:151:30: error: call of overloaded 'millis()' is ambiguous
```
I have also tried version 1.3.0 with same outcome.
Older than 1.2.0 give other errors.
What could be the problem?

**platformio.ini**
```
[env:nano33ble]
platform = nordicnrf52
board = nano33ble
framework = arduino

lib_deps = 
    tcoppex/Mbed BLE HID@1.2.0
```

**main.cpp**
```
#include <Arduino.h>
#include <USBKeyboard.h>

static USBKeyboard Keyboard;

void setup(){

}

void loop(){
  delay(1000);
  Keyboard.printf("Hello world\n\r");
} 
```

**Comment by erichstuder** [comment]
Found out it is related to this redefinition of millis() in Mbed_BLE_HID.cpp line 19.
Seems to collide with the existing definition.

```
// Redefine Arduino millis() method when on PlatformIO...
#ifdef PLATFORMIO
uint32_t millis() {
  static mbed::Timer sTimer;
  static bool bInit(false);
  if (!bInit) {
    sTimer.start();
    bInit = true;
  } 
  return sTimer.read_ms();
}
#endif
```

As it depends on PLATFORMIO this explains why it compiles in the arduino IDE.

**Comment by tcoppex** [comment]
Hi,

Yes in a previous version (MbedOS 5 I believe) `millis` was not defined, and while technically it is an arduino project, I also tend to use platformio myself.

As you noted this was causing some issues so It was ultimately replaced in the `dev` branch, which is still pending a general fix to be merged on master.

Thanks for your feedback Erich.

**Comment by erichstuder** [comment]
Thank you, I think I understand.
I have tried out using older 'platform' versions in the platformio.ini file.
No luck so far.
Same problem with 5.x.x versions.
4.x.x versions same problem or seem not to be compatible with platformio anymore as 'package.json' manifest file is missing in the package.

Is there maybe another workaround for platformio?
