### ISSUE TITLE
USBKeyboard influencing BLE?

### ISSUE THREAD

**Issue by erichstuder** [tcoppex/mbed-ble-hid#18]
Hello

I have a small arduino sketch for the Arduino Nano 33 BLE.
[firmware.zip](https://github.com/tcoppex/mbed-ble-hid/files/9054772/firmware.zip)

Board Library:
- Arduino Mbed OS Nano Boards v3.1.1
Libraries:
- ArduinoBLE v1.3.1
- Mbed BLE HID v1.3.0 or v1.2.0 (same problem with both)

I try to mix BLE functionality with the USBKeyboard.
Both individually work fine.
But as soon as I try to use both it still compiles but the Arduino crashes:
LED no longer blinking and BLE device no longer discoverable.

Is it possible that the USBKeyboard influences BLE?

**Comment by tcoppex** [comment]
I cannot say, maybe both try to pass as an HID service to the server. 
I do not believe this is an issue related to this project though (especially looking at your firmware sample), I'll close this for now.

**Comment by erichstuder** [comment]
OH MY GOD!
I fucked it up.
Of course it has nothing to do with your project.
Totally different library!
Sorry.
