### ISSUE TITLE
Issue with W7 and CRS Harmony BT adapter.

### ISSUE THREAD

**Issue by BOB63** [tcoppex/mbed-ble-hid#4]
Hi ,
this code works perfrectly with Android device and W10 PC with native BT adaperr. On my desktop with W7 and a CRS Harmony BT usb adaper  it doesn't ,because return the message "wrong code entered" , like if he try to do a pairing with pin code , while on Android and other PC isn't required the pairing with pin code. Is there any way to solve this issue ?  Tks. Roberto

**Comment by tcoppex** [comment]
Hi Roberto, thanks for your feedback.

I have no ideas nor ways to test this at the moment but you might want to check the security parameters of the ble connection. 
I'll leave the issue open for now if anyone can help you.

Cheers

**Comment by tcoppex** [comment]
I'll close this one as I believe it's related to this discussion #8 .
